### ISSUE TITLE
Site copy: Create texts for datasketch.store (description, tittles, seo...)

### ISSUE THREAD

**Issue by andescribe** [datasketch/store#13]
Escribir textos de descripción de la tienda, títulos y SEO. 

https://docs.google.com/document/d/1fd55nShjB5KnV-ubyHYC_3HF-BWjey35x_YPMnVLKSo/edit?usp=drive_web&ouid=118179245375297236332

@verotorobe

**Comment by jpmarindiaz** [comment]
Closed... duplicate of #14
